Update deploy-test.yaml

diff --git a/.github/workflows/deploy-test.yaml b/.github/workflows/deploy-test.yaml
--- a/.github/workflows/deploy-test.yaml
+++ b/.github/workflows/deploy-test.yaml
@@ -18,20 +18,16 @@ jobs:
         run: |
           echo "$SSH_KEY" > key.pem
           chmod 600 key.pem
-          ssh -tt -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST << 'EOF'
-            export IMAGE_NAME=$IMAGE_NAME &&
-            export IMAGE_TAG=$IMAGE_TAG &&
-            export WEB_FOLDER=$WEB_FOLDER &&
-            cd $WEB_FOLDER &&
-            if [ -f docker-compose.yml ]; then
-              echo "docker-compose.yml exists, proceeding with deployment."
-              docker compose down &&
-              docker rmi -f $IMAGE_NAME:$IMAGE_TAG &&
-              docker pull $IMAGE_NAME:$IMAGE_TAG &&
-              docker compose up -d
-            else
-              echo "docker-compose.yml not found in $WEB_FOLDER"
-              exit 1
-            fi
-            exit
-          EOF
+          ssh -tt -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST \
+          "export IMAGE_NAME=$IMAGE_NAME IMAGE_TAG=$IMAGE_TAG WEB_FOLDER=$WEB_FOLDER && \
+          cd $WEB_FOLDER && \
+          if [ -f docker-compose.yaml ]; then \
+            echo \"docker-compose.yml exists, proceeding with deployment.\" && \
+            docker compose down && \
+            docker rmi -f $IMAGE_NAME:$IMAGE_TAG && \
+            docker pull $IMAGE_NAME:$IMAGE_TAG && \
+            docker compose up -d; \
+          else \
+            echo \"docker-compose.yaml not found in $WEB_FOLDER\" && \
+            exit 1; \
+          fi"
